spring.application.name=reservaLab
spring.datasource.url=jdbc:mysql://localhost:3306/reserva_lab_db
spring.datasource.username=reservalab_user
spring.datasource.password=minhasenha123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true